version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  database:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

